[package]
name = "egui_glfw"
version = "0.2.1+dev"
authors = ["ishbosamiya <ishbosamiya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.18" }
glfw = "0.41"
gl = "0.14"
nalgebra-glm = "0.13"

[dev-dependencies]
copypasta-ext = "0.3"
egui_demo_lib = "0.18.0"

[[example]]
name = "simple_gui"

[[example]]
name = "demo_app"